### ISSUE TITLE
enable "strict": true in tsconfig.json

### ISSUE THREAD

**Issue by karl-run** [navikt/helsesjekk-bot#48]

**Comment by testersen** [comment]
why?

**Comment by testersen** [comment]
Did you mean set "strict" to true?

**Comment by karl-run** [comment]
Yes. :) The tsconfig was originally init'd with strict: false, there are a bunch of weak typing that needs to be addressed, especially in the bot code. Had some bugs because of this.

**Comment by testersen** [comment]
Aha! That makes more sense! Very nice :)

**Comment by karl-run** [comment]
fixed in #57
