### ISSUE TITLE
What's up with the hard coded urls?

### ISSUE THREAD

**Issue by testersen** [navikt/helsesjekk-bot#55]
https://github.com/navikt/helsesjekk-bot/blob/main/src/middleware.ts#L14

Could we get this in a .env configuration?

Thank u <3

**Comment by karl-run** [comment]
Sure. :smile: But there is a whole lot of NAV-specific code, so your fork would have to make quite a few changes for this to be deployable anywhere else :see_no_evil: 

Take a look at Politiet's fork diff: https://github.com/navikt/helsesjekk-bot/compare/main...politiet:helsesjekk-bot:main :sweat_smile:

**Comment by karl-run** [comment]
The specific code you linked to exists purely because we changed ingress at some point. That entire if is something you would delete in your fork. :smile:

**Comment by testersen** [comment]
Aha I understand! Thank you Karl! :)
