### ISSUE TITLE
Where can we find the OAuth2 handler?

### ISSUE THREAD

**Issue by testersen** [navikt/helsesjekk-bot#56]
![image](https://github.com/navikt/helsesjekk-bot/assets/125522276/5ae3c05d-8e5c-4f08-bb56-776ed2b5a9e5)

**Comment by karl-run** [comment]
In NAV this is handled by [a sidecar](https://github.com/nais/wonderwall) when deployed to the cluster. So from the application's perspective it's completely "automagic".

If you're working on your own fork, you'd have to implement these your self, I think Politiet's fork uses https://next-auth.js.org/.

**Comment by testersen** [comment]
Ah yes, that is what we ended up finding out too.

I think we've come to the conclusion that we're just going to create our own Slack integration that depends less on external factors, such as Azure groups, mostly due to having to dealing with Azure groups in our org. is not a great user experience because of red tape. Nor do I have the energy to fight with whomever makes those decisons.

We're definitely going to open-source the integration and credit this repo as the source of inspiration ;)

**Comment by karl-run** [comment]
The bot it self can easily be ran standalone with just some slack environment variables and a database. The dashboard is just a "nice to have" feature with some additional configuration options and graphs.

Just run this as a standalone entry-point in a Dockerfile: https://github.com/navikt/helsesjekk-bot/blob/main/src/bot/index.ts

**Comment by karl-run** [comment]
Ofc the bot it self is pretty simple, so if your employer lets you spend some time building your own bot I'd definitely do that. It's a lot of fun. :-)

**Comment by testersen** [comment]
Indeed! We want to have the dashboard part built-into slack using the application home feature and update slack messages ;)
